name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 
      - self-hosted
      - kyLabel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Build and test
      #   run: |
      #     # Add your build and test commands here
      #     echo "Building and testing..."

      - name: Set up .env file
        run: |
          echo "${{ secrets.ENV }}" > .env
          attrib +r .env

      - name: Build and run Docker Compose
        run: |
          # Build and run Docker Compose
          docker compose up --build -d
          docker image prune -f
